# Generated by Django 3.2 on 2022-06-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Asosiy qism')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Sana')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
